name: Build and Deploy CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install npm dependencies
      run: pnpm install && mkdir dist
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        envkey_CHATGPAT_TOKEN: ${{ secrets.CHATGPAT_TOKEN }}
        envkey_WEBHOOK_DOMAIN: 185.10.68.207
        envkey_PORT: 8841
        envkey_PROD: true
    - name: Run build task
      run: pnpm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: Git pull
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/lain/rusrusrus && git pull && pnpm i